services:
  Pusher\Pusher:
    public: true
    arguments:
      - "%env(PUSHER_KEY)%"
      - "%env(PUSHER_SECRET)%"
      - "%env(PUSHER_APP_ID)%"
      - { cluster: "%env(PUSHER_CLUSTER)%" }

lopi_pusher:
  key: "%env(PUSHER_KEY)%"
  secret: "%env(PUSHER_SECRET)%"
  app_id: "%env(PUSHER_APP_ID)%"
  cluster: "%env(PUSHER_CLUSTER)%"
